### ISSUE TITLE
Wishs

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#1]
-  If we can make it support multiple file formats (instead of just SVG) would be awesome. I think GIMP and ImageMagic both can do things with different raster file formats. For Vector svg is enough.
- We are not that excited in non open file formats such as .psd from photoshop. But GIMP new versions will support .psd and tiff. 
- If we can make it cross platform (i guess it depends on the libraries or other programmes) would be nice.

**Comment by lpsandaruwan** [comment]
Sure we can make this work for any kind of image type. But I'm not sure about making this cross-platform. Because, if we are making this , a standalone app, I'm not sure whether their are libraries similar to the opensource libraries. I think we should first look at the Unix types. :-)

**Comment by pathumego** [comment]
Unix Types is more than enough for me :) Windows is stupid anyway :P

**Comment by lpsandaruwan** [comment]
haha..  (Y)
