### ISSUE TITLE
.xcf file error

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#26]
'''
morphing images...

convert: unable to open image `/home/mooniak/animager/*.png': No such file or directory @ error/blob.c/OpenBlob/2709.
convert: unable to open file`/home/mooniak/animager/*.png' @ error/png.c/ReadPNGImage/3922.
convert: no images defined `/home/mooniak/animager/morph-cache/%05d.jpg' @ error/convert.c/ConvertImageCommand/3210.
ffmpeg version 2.5.6-0ubuntu0.15.04.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.9.2 (Ubuntu 4.9.2-10ubuntu13)
  configuration: --prefix=/usr --extra-version=0ubuntu0.15.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --shlibdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --enable-shared --disable-stripping --enable-avresample --enable-avisynth --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libshine --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libwavpack --enable-libwebp --enable-libxvid --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzvbi --enable-libzmq --enable-frei0r --enable-libvpx --enable-libx264 --enable-libsoxr --enable-gnutls --enable-openal --enable-libopencv --enable-librtmp --enable-libx265
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[image2 @ 0x1186a00] Could find no file with path '/home/mooniak/animager/morph-cache/%05d.jpg' and index in the range 0-4
/home/mooniak/animager/morph-cache/%05d.jpg: No such file or directory

Keep temporary image files ? (y/n) 
'''

**Comment by lpsandaruwan** [comment]
I tested with a .xcf file and it worked, are you sure you gave the input file name correctly ?

**Comment by lpsandaruwan** [comment]
try converting the .xcf file with this command and tell me what is the output ?
convert inputFileName.xcf outputFileName.png

**Comment by pathumego** [comment]
mooniak@mooniak-Inspiron-N5010:~$ convert '/home/mooniak/SparkleShare/animager-test/pathum.xcf' test.png
convert: memory allocation failed `/home/mooniak/SparkleShare/animager-test/pathum.xcf' @ error/xcf.c/ReadXCFImage/1338.
convert: no images defined`test.png' @ error/convert.c/ConvertImageCommand/3210.
mooniak@mooniak-Inspiron-N5010:~$

**Comment by lpsandaruwan** [comment]
Update Imagemagick. Will solve the problem.

**Comment by pathumego** [comment]
cool ill do now

**Comment by pathumego** [comment]
`ImageMagick-6.8.X` needed :)
