### ISSUE TITLE
Show a frame longer and morph to 0

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#27]
I suggest to reduce morph value to 0 and increase the change the duration of each commit frame is displayed by default.  See the video

https://www.youtube.com/watch?v=MPeK8zrkVSQ&feature=youtu.be

I think the crossfade transition is not ideal as a default setting. So we let them decide :)

Adding a option to activate and increase the morph time if needed and adding another option to change the  duration of each commit frame in milisec is the final aim. This will show up on gui as the speed of the video :)

**Comment by pathumego** [comment]
Actually  I think morph value of 2 is really nice. Here is a video.
http://youtu.be/LcpiBgUCKG8

 @lpsandaruwan  what do you think

**Comment by lpsandaruwan** [comment]
Why is this video blinking ?

**Comment by lpsandaruwan** [comment]
you can change the morph value here, in the genVideo.py file,
in line 16,
               + ' -morph 5 '

or else I can disable the morph function by default. What do you suggest??

**Comment by lpsandaruwan** [comment]
done...!!!
