### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#4]
Note: checking out '4dd6de8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 4dd6de8... Initial commit
Previous HEAD position was 4dd6de8... Initial commit
HEAD is now at 30f9e08... box
Previous HEAD position was 30f9e08... box
HEAD is now at bf071ba... scale1
Previous HEAD position was bf071ba... scale1
HEAD is now at 6c53af2... circles
Previous HEAD position was 6c53af2... circles
HEAD is now at 2e289c4... circles
Previous HEAD position was 2e289c4... circles
HEAD is now at 9860d38... copy
Previous HEAD position was 9860d38... copy
HEAD is now at 36ed6f6... delete
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

morphing images...

ffmpeg version 0.8.16-4:0.8.16-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Sep 16 2014 18:33:49 with gcc 4.6.3
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
[image2 @ 0x16948c0] max_analyze_duration reached
Input #0, image2, from 'temp/morph-cache/%05d.jpg':
  Duration: 00:00:06.35, start: 0.000000, bitrate: N/A
    Stream #0.0: Video: mjpeg, gray, 744x1052 [PAR 72:72 DAR 186:263], 20 fps, 20 tbr, 20 tbn, 20 tbc
Unrecognized option 'c:v'
Failed to set value 'h264' for option 'c:v'
pathumego@pathum-pc:~/ANIMATE-SVG-PROCESS/src/test-skeleton-python-script$

**Comment by lpsandaruwan** [comment]
This is caused by outdated or missing ffmpeg dependencies. I recommend you to install ffmpeg from this repository.

sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get install ffmpeg

**Comment by pathumego** [comment]
cool! lets put this in the set up instructions :)

**Comment by pathumego** [comment]
ok i keep getting the same error. im testing on elementy based on  ubuntu 12.04  I removed ffmpeg and installed from the ppa. but im not sure if it is properly installed when i do just ffmpeg on terminal i get this

ffmpeg version 0.8.17-4:0.8.17-0ubuntu0.12.04.1, Copyright (c) 2000-2014 the Libav developers
  built on Mar 16 2015 13:26:50 with gcc 4.6.3
The ffmpeg program is only provided for script compatibility and will be removed
in a future release. It has been deprecated in the Libav project to allow for
incompatible command line syntax improvements in its replacement called avconv
(see Changelog for details). Please use avconv instead.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by pathumego** [comment]
Tested done! it was the old ffmpeg issue
