### ISSUE TITLE
Use vagrent 

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#42]
@lpsandaruwan so we can make the CLI platform independent using a Vagrent box. @paarandika did this for font build.
Until we get the GUI up someday this would be a nice way to fix the platform problem. But i don't know if it is good practice to use something made for dev environments to package an end user software. 

Packages we need are just
-  FFMPEG
- Imagemagick
- animager

**Comment by lpsandaruwan** [comment]
Sure... I am trying to make animager work on Windows using mingw. I can try this out too.

**Comment by pathumego** [comment]
cc @paarandika
