### ISSUE TITLE
Remove temp images after video is generated

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#5]
Ask users if they need to keep the temporarily generated png images and if Yes keep them, otherwise delete them.

**Comment by lpsandaruwan** [comment]
Okay. These are just test scripts. I'm going to add more options like input, output types, and video type, video size, image size... etc. And a command line tool, you can just cd in to the directory and call the command giving arguments like, "animate-svg-process -w 320 -h 240 -t mp4 -o newvideo"
Tell me what are the options you need.

**Comment by lpsandaruwan** [comment]
After creating the command line tool we can start making the gui.

**Comment by pathumego** [comment]
Cool I'm trying to make this work for n my set up right now.. I'll test
first and let you know!

**Comment by pathumego** [comment]
YEY! works :)  I'll update the proposal.md with options :)

**Comment by lpsandaruwan** [comment]
okay. :+1:

**Comment by pathumego** [comment]
merging this issue to #6
