### ISSUE TITLE
GUI explain

### ISSUE THREAD

**Issue by pathumego** [mooniak/animate-svg-process#9]
@lpsandaruwan How will the GUI work? I can think about how it should look and interaction should be if you can tell me the limitations and other problems.

**Comment by lpsandaruwan** [comment]
Okay, my idea goes like this.
can select git folder, preset, create a new preset, delete or not temp files , select a image to put as the first slide.

GUI can be generated using QT libraries. Can come up with a basic GUI. Artwork is up to you.

**Comment by pathumego** [comment]
Cool :) @lpsandaruwan Select git folder or exact file?
